apiVersion: apps/v1
kind: Deployment
metadata: 
  name: nginx
  labels:
    app: nginx
    tier: frontend
spec: 
  replicas: {{ .Values.deployment.replicas }}
  selector: 
    matchLabels: 
      tier: frontend
      app: nginx
  template: 
    metadata:
      labels:
        tier: frontend
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:{{ .Values.deployment.imageVersion}}