apiVersion: v1
kind: Service
metadata:
  name:  nginx
spec:
  type: {{ .values.service.type}}
  selector: 
    tier: frontend
    app: nginx
  ports: 
    - name: nginx-service-port
      protocol: TCP
      port: {{ .values.service.port }}
      targetPort: 80